export const AUTHENTICATE_USER = "STORE_USER";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SIDEBAR_LINKS = "SET_SIDEBAR_LINKS";
export const CHANGE_SIDEBAR_ACTIVE = "CHANGE_SIDEBAR_ACTIVE";
export const SET_SHOP_CATEGORIES = "SET_SHOP_CATEGORIES";
